<?php

namespace App\Services;

use App\Models\Build;

class SystemMockupService
{
    protected const WIDTH = 1400;

    protected const HEIGHT = 900;

    /**
     * Render a PNG mockup of the complete system for a build.
     *
     * Component-accurate: every selected part is drawn and labelled with its
     * name and price, so the image always reflects the exact configuration.
     */
    public function render(Build $build): string
    {
        $img = imagecreatetruecolor(self::WIDTH, self::HEIGHT);

        $bg = $this->color($img, 11, 13, 18);
        $panel = $this->color($img, 18, 21, 28);
        $panelHi = $this->color($img, 24, 28, 38);
        $case = $this->color($img, 28, 32, 42);
        $stroke = $this->color($img, 48, 54, 68);
        $text = $this->color($img, 235, 237, 242);
        $muted = $this->color($img, 148, 155, 168);
        $accent = $this->color($img, 239, 68, 68);

        imagefilledrectangle($img, 0, 0, self::WIDTH, self::HEIGHT, $bg);

        $this->text($img, 'PCTG SYSTEM MOCKUP', 48, 46, $accent, 26);
        $this->text($img, $build->name, 48, 84, $text, 34);
        $this->text(
            $img,
            '£' . number_format((float) $build->total_price, 0) . '  ·  ' . strtoupper($build->resolution ?? '1440P'),
            48,
            128,
            $muted,
            20
        );

        $this->drawCase($img, $case, $stroke, $panelHi);

        $components = $build->selectedComponents->keyBy('pivot.category');

        $this->drawPsu($img, $components->get('psu'), $stroke, $text);
        $this->drawGpu($img, $components->get('gpu'), $stroke, $text);
        $this->drawMotherboard($img, $components->get('motherboard'), $components->get('cpu'), $components->get('ram'), $stroke, $text);
        $this->drawStorage($img, $components->get('storage'), $stroke, $text);
        $this->drawFans($img, $stroke, $accent);

        $this->drawPartsList($img, $components, $text, $muted);

        $this->text($img, 'Generated by PCTG Builder · prices as confirmed', 48, self::HEIGHT - 34, $muted, 16);

        ob_start();
        imagepng($img);
        $png = (string) ob_get_clean();
        imagedestroy($img);

        return $png;
    }

    protected function drawCase($img, $case, $stroke, $panelHi): void
    {
        $x = 40;
        $y = 170;
        $w = 560;
        $h = 620;

        imagefilledrectangle($img, $x, $y, $x + $w, $y + $h, $case);
        imagerectangle($img, $x, $y, $x + $w, $y + $h, $stroke);

        imagefilledrectangle($img, $x + 10, $y + 10, $x + 160, $y + $h - 10, $panelHi);
        imagerectangle($img, $x + 10, $y + 10, $x + 160, $y + $h - 10, $stroke);

        $this->text($img, 'PCTG', $x + 52, $y + 48, $this->color($img, 239, 68, 68), 30);

        for ($i = 0; $i < 3; $i++) {
            $fy = $y + 120 + ($i * 130);
            imagefilledrectangle($img, $x + 40, $fy, $x + 130, $fy + 90, $this->color($img, 14, 17, 23));
            imagerectangle($img, $x + 40, $fy, $x + 130, $fy + 90, $stroke);
        }

        imagefilledrectangle($img, $x + 180, $y + 10, $x + $w - 10, $y + $h - 10, $this->color($img, 16, 19, 26));
        imagerectangle($img, $x + 180, $y + 10, $x + $w - 10, $y + $h - 10, $stroke);
    }

    protected function drawMotherboard($img, $board, $cpu, $ram, $stroke, $text): void
    {
        $bx = 260;
        $by = 200;
        $bw = 280;
        $bh = 330;

        $boardColor = $this->color($img, 40, 44, 58);

        if ($board) {
            $name = mb_strtolower((string) $board->name);
            if (str_contains($name, 'gigabyte')) {
                $boardColor = $this->color($img, 38, 52, 66);
            } elseif (str_contains($name, 'asus')) {
                $boardColor = $this->color($img, 42, 40, 60);
            }
        }

        imagefilledrectangle($img, $bx, $by, $bx + $bw, $by + $bh, $boardColor);
        imagerectangle($img, $bx, $by, $bx + $bw, $by + $bh, $stroke);

        if ($cpu) {
            $cx = $bx + 90;
            $cy = $by + 60;
            imagefilledrectangle($img, $cx, $cy, $cx + 110, $cy + 110, $this->color($img, 70, 62, 40));
            imagerectangle($img, $cx, $cy, $cx + 110, $cy + 110, $stroke);
            imagefilledellipse($img, $cx + 55, $cy + 55, 76, 76, $this->color($img, 120, 106, 60));
            $this->label($img, $cpu->name, $cx + 55, $cy + 150, $text);
        }

        if ($ram) {
            $rx = $bx + 225;
            for ($i = 0; $i < 2; $i++) {
                imagefilledrectangle($img, $rx + ($i * 22), $by + 48, $rx + ($i * 22) + 14, $by + 150, $this->color($img, 110, 56, 120));
                imagerectangle($img, $rx + ($i * 22), $by + 48, $rx + ($i * 22) + 14, $by + 150, $stroke);
            }
            $this->label($img, $ram->name, $rx + 14, $by + 176, $text);
        }

        if ($board) {
            $this->label($img, $board->name, $bx + $bw / 2, $by + $bh + 30, $text);
        }

        for ($i = 0; $i < 4; $i++) {
            imagefilledrectangle($img, $bx + 20 + ($i * 20), $by + $bh - 60, $bx + 34 + ($i * 20), $by + $bh - 8, $this->color($img, 92, 98, 120));
        }
    }

    protected function drawGpu($img, $gpu, $stroke, $text): void
    {
        if (! $gpu) {
            return;
        }

        $gx = 260;
        $gy = 560;
        $gw = 340;
        $gh = 90;

        $color = $this->color($img, 34, 40, 34);
        $name = mb_strtolower((string) $gpu->name);
        if (str_contains($name, 'radeon') || str_contains($name, 'rx')) {
            $color = $this->color($img, 54, 34, 34);
        }

        imagefilledrectangle($img, $gx, $gy, $gx + $gw, $gy + $gh, $color);
        imagerectangle($img, $gx, $gy, $gx + $gw, $gy + $gh, $stroke);

        for ($i = 0; $i < 3; $i++) {
            imagefilledellipse($img, $gx + 60 + ($i * 80), $gy + 45, 52, 52, $this->color($img, 20, 23, 30));
            imagerectangle($img, $gx + 60 + ($i * 80) - 26, $gy + 45 - 26, $gx + 60 + ($i * 80) + 26, $gy + 45 + 26, $stroke);
        }

        $this->label($img, $gpu->name, $gx + $gw / 2, $gy - 26, $text);
    }

    protected function drawPsu($img, $psu, $stroke, $text): void
    {
        $px = 240;
        $py = 720;
        $pw = 300;
        $ph = 60;

        imagefilledrectangle($img, $px, $py, $px + $pw, $py + $ph, $this->color($img, 52, 54, 62));
        imagerectangle($img, $px, $py, $px + $pw, $py + $ph, $stroke);

        if ($psu) {
            $this->label($img, $psu->name . ' · ' . ($psu->wattage ?? '') . 'W', $px + $pw / 2, $py - 24, $text);
        } else {
            $this->label($img, 'Power Supply', $px + $pw / 2, $py - 24, $text);
        }
    }

    protected function drawStorage($img, $storage, $stroke, $text): void
    {
        if (! $storage) {
            return;
        }

        $sx = 260;
        $sy = 500;
        $sw = 180;
        $sh = 34;

        imagefilledrectangle($img, $sx, $sy, $sx + $sw, $sy + $sh, $this->color($img, 30, 48, 46));
        imagerectangle($img, $sx, $sy, $sx + $sw, $sy + $sh, $stroke);
        $this->label($img, $storage->name, $sx + $sw / 2, $sy - 22, $text);
    }

    protected function drawFans($img, $stroke, $accent): void
    {
        $x = 220;
        $y = 200;
        for ($i = 0; $i < 2; $i++) {
            imagefilledellipse($img, $x + ($i * 60), $y, 44, 44, $this->color($img, 20, 23, 30));
            imageellipse($img, $x + ($i * 60), $y, 44, 44, $stroke);
            imagefilledellipse($img, $x + ($i * 60), $y, 10, 10, $accent);
        }
    }

    protected function drawPartsList($img, $components, $text, $muted): void
    {
        $lx = 680;
        $ly = 210;
        $line = 52;

        $this->text($img, 'SELECTED COMPONENTS', $lx, $ly - 26, $muted, 22);

        $categoryLabels = [
            'cpu' => 'CPU',
            'motherboard' => 'Motherboard',
            'gpu' => 'Graphics Card',
            'ram' => 'Memory',
            'storage' => 'Storage',
            'psu' => 'Power Supply',
            'case' => 'Case',
        ];

        $total = 0;

        foreach ($categoryLabels as $category => $label) {
            $component = $components->get($category);
            $y = $ly + $line * ($category === 'cpu' ? 0 : array_search($category, array_keys($categoryLabels), true));

            if ($component) {
                $total += (float) $component->pivot->price_snapshot;
                $this->text($img, $label, $lx, $y, $muted, 18);
                $this->text($img, $component->name, $lx + 160, $y, $text, 18);
                $this->text($img, '£' . number_format((float) $component->pivot->price_snapshot, 0), $lx + 560, $y, $text, 18);
            }
        }

        $this->line($img, $lx, $ly + $line * 7 - 8, $lx + 620, $ly + $line * 7 - 8, $muted);

        $this->text($img, 'Components total', $lx, $ly + $line * 7 + 10, $muted, 18);
        $this->text($img, '£' . number_format($total, 0), $lx + 560, $ly + $line * 7 + 10, $text, 20);
    }

    protected function label($img, string $text, int $x, int $y, $color): void
    {
        $text = $this->truncate($text, 30);

        if ($this->font() === null) {
            imagestring($img, 5, $x, $y - 12, $text, $color);

            return;
        }

        $bbox = imagettfbbox(15, 0, $this->font(), $text);
        $w = ($bbox[2] - $bbox[0]) / 2;
        $this->text($img, $text, (int) ($x - $w), $y, $color, 15);
    }

    protected function truncate(string $text, int $max): string
    {
        if (mb_strlen($text) <= $max) {
            return $text;
        }

        return mb_substr($text, 0, $max - 1) . '…';
    }

    protected function text($img, string $text, int $x, int $y, $color, int $size): void
    {
        $text = $this->truncate($text, 42);

        if ($this->font() === null) {
            imagestring($img, (int) max(1, min(5, (int) round($size / 10))), $x, $y - $size, $text, $color);

            return;
        }

        imagettftext($img, $size, 0, $x, $y, $color, $this->font(), $text);
    }

    protected function line($img, int $x1, int $y1, int $x2, int $y2, $color): void
    {
        imageline($img, $x1, $y1, $x2, $y2, $color);
    }

    protected function color($img, int $r, int $g, int $b): int
    {
        return imagecolorallocate($img, $r, $g, $b);
    }

    protected function font(): ?string
    {
        static $font;

        if (isset($font)) {
            return $font;
        }

        $candidates = [
            'C:\Windows\Fonts\arial.ttf',
            'C:\Windows\Fonts\arialbd.ttf',
            '/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf',
            '/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf',
            '/usr/share/fonts/dejavu/DejaVuSans.ttf',
            '/System/Library/Fonts/Helvetica.ttc',
        ];

        foreach ($candidates as $candidate) {
            if (is_file($candidate)) {
                return $font = $candidate;
            }
        }

        return $font = null;
    }
}
